[package]
name = "fletch"
version = "0.1.0"
edition = "2024"

[dependencies]
bumpalo = "3.20.3"
clap = { version = "4.6.1", features = ["derive"] }
codespan-reporting = "0.13.1"
cranelift = "0.133.1"
cranelift-jit = "0.133.1"
fnv = "1.0.7"
hashbrown = "0.17.1"
itertools = "0.14.0"
line-index = "0.1.2"
log = "0.4.33"
logos = "0.16.1"
memmap2 = "0.9.11"
num-bigint = "0.5.1"
ordered-float = "5.3.0"
paste = "1.0.15"
serde = { version = "1.0.228", features = ["derive"] }
tap = "1.0.1"
target-lexicon = "0.13.5"
thiserror = "2.0.18"
triomphe = "0.1.15"
